[2021-12-21 23:12:04,399] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.sketch scheduled__2021-12-19T00:18:00+00:00 [queued]>
[2021-12-21 23:12:04,404] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline.sketch scheduled__2021-12-19T00:18:00+00:00 [queued]>
[2021-12-21 23:12:04,404] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 23:12:04,404] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-21 23:12:04,404] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-21 23:12:04,413] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): sketch> on 2021-12-19 00:18:00+00:00
[2021-12-21 23:12:04,416] {standard_task_runner.py:52} INFO - Started process 105261 to run task
[2021-12-21 23:12:04,420] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'sketch', 'scheduled__2021-12-19T00:18:00+00:00', '--job-id', '210', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpzi520b9d', '--error-file', '/tmp/tmpnie1jdab']
[2021-12-21 23:12:04,421] {standard_task_runner.py:77} INFO - Job 210: Subtask sketch
[2021-12-21 23:12:04,445] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline.sketch scheduled__2021-12-19T00:18:00+00:00 [running]> on host myamya
[2021-12-21 23:12:04,469] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=sketch
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T00:18:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T00:18:00+00:00
[2021-12-21 23:12:04,469] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-21 23:12:04,469] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sketch:0.4 /bin/bash /home/myamya/project/init.sh ']
[2021-12-21 23:12:04,473] {subprocess.py:85} INFO - Output:
[2021-12-21 23:12:12,510] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-21 23:12:12,541] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=sketch, execution_date=20211219T001800, start_date=20211221T141204, end_date=20211221T141212
[2021-12-21 23:12:12,591] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-21 23:12:12,606] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
