[2021-12-22 18:05:05,857] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:46:00+00:00 [queued]>
[2021-12-22 18:05:05,861] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:46:00+00:00 [queued]>
[2021-12-22 18:05:05,861] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 18:05:05,861] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-22 18:05:05,861] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 18:05:05,869] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): sketch> on 2021-12-20 00:46:00+00:00
[2021-12-22 18:05:05,871] {standard_task_runner.py:52} INFO - Started process 39754 to run task
[2021-12-22 18:05:05,873] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'sketch', 'scheduled__2021-12-20T00:46:00+00:00', '--job-id', '261', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp8jg7w0ik', '--error-file', '/tmp/tmponvfbtmg']
[2021-12-22 18:05:05,873] {standard_task_runner.py:77} INFO - Job 261: Subtask sketch
[2021-12-22 18:05:05,891] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:46:00+00:00 [running]> on host myamya
[2021-12-22 18:05:05,918] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=sketch
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:46:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:46:00+00:00
[2021-12-22 18:05:05,920] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 18:05:05,921] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sketch:0.4 /bin/bash /home/myamya/project/init.sh ']
[2021-12-22 18:05:05,936] {subprocess.py:85} INFO - Output:
[2021-12-22 18:05:33,410] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 18:05:33,433] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=sketch, execution_date=20211220T004600, start_date=20211222T090505, end_date=20211222T090533
[2021-12-22 18:05:33,485] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 18:05:33,500] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
