[2021-12-22 17:32:21,975] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:24:00+00:00 [queued]>
[2021-12-22 17:32:21,978] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:24:00+00:00 [queued]>
[2021-12-22 17:32:21,978] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:32:21,978] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-22 17:32:21,979] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:32:21,987] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): face_crop> on 2021-12-20 00:24:00+00:00
[2021-12-22 17:32:21,988] {standard_task_runner.py:52} INFO - Started process 26296 to run task
[2021-12-22 17:32:21,990] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'face_crop', 'scheduled__2021-12-20T00:24:00+00:00', '--job-id', '129', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpuarixsav', '--error-file', '/tmp/tmppl1oale4']
[2021-12-22 17:32:21,991] {standard_task_runner.py:77} INFO - Job 129: Subtask face_crop
[2021-12-22 17:32:22,008] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.face_crop scheduled__2021-12-20T00:24:00+00:00 [running]> on host myamya
[2021-12-22 17:32:22,035] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=face_crop
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:24:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:24:00+00:00
[2021-12-22 17:32:22,037] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:32:22,038] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ google_api:0.8 /bin/bash init.sh ']
[2021-12-22 17:32:22,051] {subprocess.py:85} INFO - Output:
[2021-12-22 17:32:22,862] {subprocess.py:89} INFO - 0
[2021-12-22 17:32:22,862] {subprocess.py:89} INFO - 2
[2021-12-22 17:32:22,862] {subprocess.py:89} INFO - 3
[2021-12-22 17:32:22,862] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2264.jpg
[2021-12-22 17:32:24,011] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/2264.jpg: Find face from in position [31, 39, 621, 725] and skew angle [0.83626616, 1.2407098, -0.2966359]
[2021-12-22 17:32:24,310] {subprocess.py:89} INFO - [Info]  /home/myamya/project/image_files/images/2264.jpg: Crop face [31, 39, 621, 725] and write it to file : /home/myamya/project/image_files/cropped_image/2264.jpg
[2021-12-22 17:32:24,310] {subprocess.py:89} INFO - training 1
[2021-12-22 17:32:24,310] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2266.jpg
[2021-12-22 17:32:24,993] {subprocess.py:89} INFO - [Info] /home/myamya/project/image_files/images/2266.jpg: Find face from in position [31, 39, 621, 725] and skew angle [0.83626616, 1.2407098, -0.2966359]
[2021-12-22 17:32:25,281] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2266.jpg: Duplicated image
[2021-12-22 17:32:25,281] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2263.jpeg
[2021-12-22 17:32:25,773] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2263.jpeg: cannot process file : 'y'
[2021-12-22 17:32:25,773] {subprocess.py:89} INFO - @@ /home/myamya/project/image_files/images/2265.jpeg
[2021-12-22 17:32:26,216] {subprocess.py:89} INFO - [Error] /home/myamya/project/image_files/images/2265.jpeg: cannot process file : 'y'
[2021-12-22 17:32:26,216] {subprocess.py:89} INFO - ## label 1 has 1 of training data
[2021-12-22 17:32:26,216] {subprocess.py:89} INFO - number of datas per label  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2021-12-22 17:32:26,480] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:32:26,498] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=face_crop, execution_date=20211220T002400, start_date=20211222T083221, end_date=20211222T083226
[2021-12-22 17:32:26,542] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:32:26,561] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
