[2021-12-22 17:46:34,153] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:36:00+00:00 [queued]>
[2021-12-22 17:46:34,156] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:36:00+00:00 [queued]>
[2021-12-22 17:46:34,156] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:46:34,156] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-22 17:46:34,156] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:46:34,165] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): super_resolution> on 2021-12-20 00:36:00+00:00
[2021-12-22 17:46:34,167] {standard_task_runner.py:52} INFO - Started process 33584 to run task
[2021-12-22 17:46:34,169] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'super_resolution', 'scheduled__2021-12-20T00:36:00+00:00', '--job-id', '195', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp_p2nz41w', '--error-file', '/tmp/tmps96baxuz']
[2021-12-22 17:46:34,169] {standard_task_runner.py:77} INFO - Job 195: Subtask super_resolution
[2021-12-22 17:46:34,186] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:36:00+00:00 [running]> on host myamya
[2021-12-22 17:46:34,232] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=super_resolution
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:36:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:36:00+00:00
[2021-12-22 17:46:34,232] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:46:34,233] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sure:0.3 /bin/bash /home/myamya/project/init.sh ']
[2021-12-22 17:46:34,239] {subprocess.py:85} INFO - Output:
[2021-12-22 17:46:35,935] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDAFunctions.cpp:100.)
[2021-12-22 17:46:35,935] {subprocess.py:89} INFO -   return torch._C._cuda_getDeviceCount() > 0
[2021-12-22 17:46:36,948] {subprocess.py:89} INFO - Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to /opt/conda/lib/python3.8/site-packages/facexlib/weights/detection_Resnet50_Final.pth
[2021-12-22 17:46:36,948] {subprocess.py:89} INFO - 
[2021-12-22 17:46:40,169] {subprocess.py:89} INFO -   0% 0.00/104M [00:00<?, ?B/s]  0% 104k/104M [00:00<01:58, 922kB/s]  0% 392k/104M [00:00<01:34, 1.16MB/s]  1% 1.23M/104M [00:00<01:09, 1.57MB/s]  4% 3.98M/104M [00:00<00:48, 2.19MB/s]  9% 9.09M/104M [00:00<00:32, 3.07MB/s] 13% 14.0M/104M [00:00<00:22, 4.28MB/s] 18% 18.9M/104M [00:00<00:15, 5.90MB/s] 23% 23.9M/104M [00:00<00:10, 8.04MB/s] 28% 28.9M/104M [00:00<00:07, 10.8MB/s] 32% 33.9M/104M [00:01<00:05, 14.1MB/s] 37% 38.9M/104M [00:01<00:03, 18.1MB/s] 42% 43.9M/104M [00:01<00:02, 22.5MB/s] 47% 48.7M/104M [00:01<00:02, 27.0MB/s] 51% 53.8M/104M [00:01<00:01, 31.7MB/s] 56% 58.6M/104M [00:01<00:01, 35.6MB/s] 61% 63.5M/104M [00:01<00:01, 39.2MB/s] 66% 68.5M/104M [00:01<00:00, 42.3MB/s] 70% 73.3M/104M [00:01<00:00, 44.0MB/s] 75% 78.6M/104M [00:01<00:00, 46.7MB/s] 80% 83.5M/104M [00:02<00:00, 48.0MB/s] 85% 88.4M/104M [00:02<00:00, 49.0MB/s] 90% 93.5M/104M [00:02<00:00, 50.2MB/s] 94% 98.5M/104M [00:02<00:00, 44.8MB/s] 99% 103M/104M [00:02<00:00, 42.1MB/s] 100% 104M/104M [00:02<00:00, 43.2MB/s]
[2021-12-22 17:46:40,313] {subprocess.py:89} INFO - Downloading: "https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth" to /opt/conda/lib/python3.8/site-packages/gfpgan/weights/GFPGANCleanv1-NoCE-C2.pth
[2021-12-22 17:46:40,313] {subprocess.py:89} INFO - 
[2021-12-22 17:46:48,391] {subprocess.py:89} INFO -   0% 0.00/332M [00:00<?, ?B/s]  0% 176k/332M [00:00<03:16, 1.77MB/s]  0% 0.98M/332M [00:00<02:29, 2.32MB/s]  1% 4.48M/332M [00:00<01:47, 3.20MB/s]  2% 7.96M/332M [00:00<01:17, 4.40MB/s]  4% 13.3M/332M [00:00<00:54, 6.09MB/s]  5% 16.5M/332M [00:00<00:41, 8.05MB/s]  7% 21.9M/332M [00:00<00:30, 10.8MB/s]  8% 27.3M/332M [00:00<00:22, 14.3MB/s]  9% 31.5M/332M [00:00<00:18, 17.5MB/s] 11% 37.0M/332M [00:01<00:14, 22.1MB/s] 13% 42.4M/332M [00:01<00:11, 27.1MB/s] 14% 47.2M/332M [00:01<00:10, 29.4MB/s] 16% 52.6M/332M [00:01<00:08, 34.3MB/s] 17% 57.2M/332M [00:01<00:08, 35.4MB/s] 19% 62.6M/332M [00:01<00:07, 39.8MB/s] 20% 68.0M/332M [00:01<00:06, 43.7MB/s] 22% 72.9M/332M [00:01<00:06, 42.6MB/s] 23% 78.0M/332M [00:01<00:05, 45.3MB/s] 25% 83.4M/332M [00:02<00:05, 48.3MB/s] 27% 88.4M/332M [00:02<00:05, 45.8MB/s] 28% 93.4M/332M [00:02<00:05, 47.6MB/s] 30% 98.8M/332M [00:02<00:04, 50.0MB/s] 31% 104M/332M [00:02<00:05, 47.6MB/s]  33% 108M/332M [00:02<00:04, 48.1MB/s] 34% 114M/332M [00:02<00:04, 50.4MB/s] 36% 119M/332M [00:02<00:04, 46.0MB/s] 37% 124M/332M [00:02<00:04, 48.8MB/s] 39% 130M/332M [00:03<00:04, 50.9MB/s] 40% 135M/332M [00:03<00:04, 46.4MB/s] 42% 140M/332M [00:03<00:04, 49.1MB/s] 44% 145M/332M [00:03<00:04, 45.4MB/s] 45% 150M/332M [00:03<00:03, 48.2MB/s] 47% 156M/332M [00:03<00:03, 50.5MB/s] 48% 161M/332M [00:03<00:03, 47.1MB/s] 50% 166M/332M [00:03<00:03, 48.6MB/s] 51% 171M/332M [00:03<00:03, 50.9MB/s] 53% 176M/332M [00:04<00:03, 48.2MB/s] 54% 181M/332M [00:04<00:03, 48.5MB/s] 56% 186M/332M [00:04<00:03, 50.7MB/s] 57% 191M/332M [00:04<00:03, 46.1MB/s] 59% 197M/332M [00:04<00:02, 48.9MB/s] 61% 202M/332M [00:04<00:02, 51.0MB/s] 62% 207M/332M [00:04<00:02, 46.6MB/s] 64% 212M/332M [00:04<00:02, 49.3MB/s] 65% 217M/332M [00:04<00:02, 45.9MB/s] 67% 222M/332M [00:05<00:02, 48.1MB/s] 69% 228M/332M [00:05<00:02, 50.5MB/s] 70% 233M/332M [00:05<00:02, 47.4MB/s] 71% 238M/332M [00:05<00:02, 48.5MB/s] 73% 243M/332M [00:05<00:01, 50.8MB/s] 75% 248M/332M [00:05<00:01, 48.4MB/s] 76% 253M/332M [00:05<00:01, 48.1MB/s] 78% 258M/332M [00:05<00:01, 50.4MB/s] 79% 263M/332M [00:05<00:01, 46.1MB/s] 81% 268M/332M [00:06<00:01, 48.9MB/s] 82% 274M/332M [00:06<00:01, 45.3MB/s] 84% 279M/332M [00:06<00:01, 48.3MB/s] 86% 285M/332M [00:06<00:00, 50.6MB/s] 87% 290M/332M [00:06<00:00, 47.4MB/s] 89% 295M/332M [00:06<00:00, 48.9MB/s] 90% 300M/332M [00:06<00:00, 51.0MB/s] 92% 305M/332M [00:06<00:00, 48.5MB/s] 93% 310M/332M [00:06<00:00, 48.5MB/s] 95% 315M/332M [00:07<00:00, 50.6MB/s] 96% 320M/332M [00:07<00:00, 48.5MB/s] 98% 325M/332M [00:07<00:00, 48.1MB/s] 99% 330M/332M [00:07<00:00, 50.4MB/s]100% 332M/332M [00:07<00:00, 46.8MB/s]
[2021-12-22 17:46:48,571] {subprocess.py:89} INFO - Testing 0 2263
[2021-12-22 17:46:48,693] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
[2021-12-22 17:46:48,693] {subprocess.py:89} INFO -   warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
[2021-12-22 17:46:53,004] {subprocess.py:89} INFO - Testing 1 2264
[2021-12-22 17:46:58,834] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:46:58,848] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=super_resolution, execution_date=20211220T003600, start_date=20211222T084634, end_date=20211222T084658
[2021-12-22 17:46:58,894] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:46:58,936] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
