[2021-12-22 17:38:39,716] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:27:00+00:00 [queued]>
[2021-12-22 17:38:39,721] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:27:00+00:00 [queued]>
[2021-12-22 17:38:39,721] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:38:39,721] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-22 17:38:39,721] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:38:39,730] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): super_resolution> on 2021-12-20 00:27:00+00:00
[2021-12-22 17:38:39,733] {standard_task_runner.py:52} INFO - Started process 30462 to run task
[2021-12-22 17:38:39,737] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'super_resolution', 'scheduled__2021-12-20T00:27:00+00:00', '--job-id', '162', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpz8_zjys3', '--error-file', '/tmp/tmp_6ltf2v5']
[2021-12-22 17:38:39,738] {standard_task_runner.py:77} INFO - Job 162: Subtask super_resolution
[2021-12-22 17:38:39,756] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:27:00+00:00 [running]> on host myamya
[2021-12-22 17:38:39,800] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=super_resolution
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:27:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:27:00+00:00
[2021-12-22 17:38:39,801] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:38:39,802] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sure:0.3 /bin/bash /home/myamya/project/init.sh ']
[2021-12-22 17:38:39,809] {subprocess.py:85} INFO - Output:
[2021-12-22 17:38:41,438] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDAFunctions.cpp:100.)
[2021-12-22 17:38:41,438] {subprocess.py:89} INFO -   return torch._C._cuda_getDeviceCount() > 0
[2021-12-22 17:38:42,438] {subprocess.py:89} INFO - Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to /opt/conda/lib/python3.8/site-packages/facexlib/weights/detection_Resnet50_Final.pth
[2021-12-22 17:38:42,438] {subprocess.py:89} INFO - 
[2021-12-22 17:38:45,549] {subprocess.py:89} INFO -   0% 0.00/104M [00:00<?, ?B/s]  0% 224k/104M [00:00<00:54, 2.02MB/s]  2% 1.93M/104M [00:00<00:38, 2.76MB/s]  4% 4.65M/104M [00:00<00:27, 3.78MB/s]  7% 7.79M/104M [00:00<00:19, 5.13MB/s] 12% 13.0M/104M [00:00<00:13, 7.04MB/s] 16% 17.0M/104M [00:00<00:09, 9.37MB/s] 20% 21.1M/104M [00:00<00:07, 12.2MB/s] 24% 25.0M/104M [00:00<00:05, 15.5MB/s] 28% 29.2M/104M [00:00<00:04, 19.3MB/s] 32% 33.2M/104M [00:01<00:03, 22.9MB/s] 36% 37.5M/104M [00:01<00:02, 26.8MB/s] 40% 41.6M/104M [00:01<00:02, 30.2MB/s] 44% 45.7M/104M [00:01<00:01, 33.3MB/s] 48% 49.8M/104M [00:01<00:01, 35.6MB/s] 52% 54.1M/104M [00:01<00:01, 37.9MB/s] 56% 58.5M/104M [00:01<00:01, 40.1MB/s] 60% 62.7M/104M [00:01<00:01, 41.0MB/s] 64% 67.0M/104M [00:01<00:00, 42.2MB/s] 68% 71.3M/104M [00:01<00:00, 43.0MB/s] 72% 75.6M/104M [00:02<00:00, 43.7MB/s] 77% 79.9M/104M [00:02<00:00, 44.0MB/s] 81% 84.3M/104M [00:02<00:00, 44.5MB/s] 85% 88.7M/104M [00:02<00:00, 45.0MB/s] 89% 93.1M/104M [00:02<00:00, 45.3MB/s] 93% 97.5M/104M [00:02<00:00, 45.7MB/s] 98% 102M/104M [00:02<00:00, 45.8MB/s] 100% 104M/104M [00:02<00:00, 40.7MB/s]
[2021-12-22 17:38:45,696] {subprocess.py:89} INFO - Downloading: "https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth" to /opt/conda/lib/python3.8/site-packages/gfpgan/weights/GFPGANCleanv1-NoCE-C2.pth
[2021-12-22 17:38:45,696] {subprocess.py:89} INFO - 
[2021-12-22 17:38:53,691] {subprocess.py:89} INFO -   0% 0.00/332M [00:00<?, ?B/s]  0% 248k/332M [00:00<02:36, 2.23MB/s]  1% 2.07M/332M [00:00<01:54, 3.03MB/s]  1% 4.63M/332M [00:00<01:23, 4.13MB/s]  2% 7.87M/332M [00:00<01:00, 5.59MB/s]  4% 13.1M/332M [00:00<00:43, 7.65MB/s]  5% 17.1M/332M [00:00<00:32, 10.1MB/s]  6% 21.2M/332M [00:00<00:24, 13.1MB/s]  8% 25.1M/332M [00:00<00:19, 16.5MB/s]  9% 29.3M/332M [00:00<00:15, 20.3MB/s] 10% 33.3M/332M [00:01<00:13, 24.0MB/s] 11% 37.6M/332M [00:01<00:11, 27.9MB/s] 13% 41.6M/332M [00:01<00:09, 31.1MB/s] 14% 45.8M/332M [00:01<00:08, 34.1MB/s] 15% 50.0M/332M [00:01<00:08, 36.5MB/s] 16% 54.1M/332M [00:01<00:07, 38.2MB/s] 18% 58.5M/332M [00:01<00:07, 40.3MB/s] 19% 62.7M/332M [00:01<00:06, 41.1MB/s] 20% 67.2M/332M [00:01<00:06, 42.6MB/s] 21% 71.4M/332M [00:01<00:06, 43.0MB/s] 23% 75.8M/332M [00:02<00:06, 43.6MB/s] 24% 80.1M/332M [00:02<00:05, 44.3MB/s] 25% 84.4M/332M [00:02<00:05, 44.4MB/s] 27% 88.9M/332M [00:02<00:05, 45.1MB/s] 28% 93.2M/332M [00:02<00:05, 45.1MB/s] 29% 97.7M/332M [00:02<00:05, 45.6MB/s] 31% 102M/332M [00:02<00:05, 45.7MB/s]  32% 107M/332M [00:02<00:05, 46.2MB/s] 33% 111M/332M [00:02<00:05, 46.2MB/s] 35% 116M/332M [00:02<00:04, 46.5MB/s] 36% 120M/332M [00:03<00:04, 46.4MB/s] 37% 125M/332M [00:03<00:04, 46.7MB/s] 39% 129M/332M [00:03<00:04, 47.1MB/s] 40% 134M/332M [00:03<00:04, 47.0MB/s] 42% 138M/332M [00:03<00:04, 47.5MB/s] 43% 143M/332M [00:03<00:04, 47.4MB/s] 44% 147M/332M [00:03<00:04, 47.7MB/s] 46% 152M/332M [00:03<00:03, 47.8MB/s] 47% 157M/332M [00:03<00:03, 48.0MB/s] 49% 161M/332M [00:03<00:03, 48.0MB/s] 50% 166M/332M [00:04<00:03, 48.0MB/s] 51% 171M/332M [00:04<00:03, 48.3MB/s] 53% 175M/332M [00:04<00:03, 48.1MB/s] 54% 180M/332M [00:04<00:03, 48.6MB/s] 56% 185M/332M [00:04<00:03, 48.1MB/s] 57% 189M/332M [00:04<00:03, 48.8MB/s] 58% 194M/332M [00:04<00:03, 48.3MB/s] 60% 199M/332M [00:04<00:02, 48.7MB/s] 61% 204M/332M [00:04<00:02, 49.2MB/s] 63% 208M/332M [00:04<00:02, 48.3MB/s] 64% 213M/332M [00:05<00:02, 49.1MB/s] 66% 218M/332M [00:05<00:02, 49.2MB/s] 67% 223M/332M [00:05<00:02, 49.3MB/s] 68% 227M/332M [00:05<00:02, 49.4MB/s] 70% 232M/332M [00:05<00:02, 49.4MB/s] 71% 237M/332M [00:05<00:02, 49.4MB/s] 73% 242M/332M [00:05<00:01, 49.5MB/s] 74% 246M/332M [00:05<00:01, 49.6MB/s] 76% 251M/332M [00:05<00:01, 49.7MB/s] 77% 256M/332M [00:05<00:01, 49.8MB/s] 78% 261M/332M [00:06<00:01, 49.7MB/s] 80% 265M/332M [00:06<00:01, 49.8MB/s] 81% 270M/332M [00:06<00:01, 49.7MB/s] 83% 275M/332M [00:06<00:01, 50.0MB/s] 84% 280M/332M [00:06<00:01, 49.8MB/s] 86% 285M/332M [00:06<00:01, 49.9MB/s] 87% 289M/332M [00:06<00:00, 49.9MB/s] 88% 294M/332M [00:06<00:00, 49.9MB/s] 90% 299M/332M [00:06<00:00, 49.6MB/s] 91% 304M/332M [00:06<00:00, 50.0MB/s] 93% 308M/332M [00:07<00:00, 50.1MB/s] 94% 313M/332M [00:07<00:00, 50.0MB/s] 96% 318M/332M [00:07<00:00, 50.1MB/s] 97% 323M/332M [00:07<00:00, 49.9MB/s] 99% 328M/332M [00:07<00:00, 46.4MB/s]100% 332M/332M [00:07<00:00, 45.9MB/s]
[2021-12-22 17:38:53,845] {subprocess.py:89} INFO - Testing 0 2264
[2021-12-22 17:38:53,950] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
[2021-12-22 17:38:53,950] {subprocess.py:89} INFO -   warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
[2021-12-22 17:38:58,503] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:38:58,516] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=super_resolution, execution_date=20211220T002700, start_date=20211222T083839, end_date=20211222T083858
[2021-12-22 17:38:58,561] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:38:58,583] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
