[2021-12-21 23:14:20,888] {taskinstance.py:1025} INFO - Dependencies not met for <TaskInstance: data_pipeline.face_crop scheduled__2021-12-19T00:26:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-12-21 23:14:20,888] {local_task_job.py:99} INFO - Task is not able to be run
