[2021-12-22 18:04:37,054] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:45:00+00:00 [queued]>
[2021-12-22 18:04:37,058] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:45:00+00:00 [queued]>
[2021-12-22 18:04:37,058] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 18:04:37,058] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-22 18:04:37,058] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 18:04:37,067] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): sketch> on 2021-12-20 00:45:00+00:00
[2021-12-22 18:04:37,071] {standard_task_runner.py:52} INFO - Started process 39617 to run task
[2021-12-22 18:04:37,076] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'sketch', 'scheduled__2021-12-20T00:45:00+00:00', '--job-id', '260', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmp0dqm2p9k', '--error-file', '/tmp/tmpoj2urxr1']
[2021-12-22 18:04:37,077] {standard_task_runner.py:77} INFO - Job 260: Subtask sketch
[2021-12-22 18:04:37,102] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.sketch scheduled__2021-12-20T00:45:00+00:00 [running]> on host myamya
[2021-12-22 18:04:37,139] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=sketch
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:45:00+00:00
[2021-12-22 18:04:37,140] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 18:04:37,141] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sketch:0.4 /bin/bash /home/myamya/project/init.sh ']
[2021-12-22 18:04:37,149] {subprocess.py:85} INFO - Output:
[2021-12-22 18:05:04,701] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 18:05:04,745] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=sketch, execution_date=20211220T004500, start_date=20211222T090437, end_date=20211222T090504
[2021-12-22 18:05:04,771] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 18:05:04,790] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
