[2021-12-22 17:28:14,098] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:17:00+00:00 [queued]>
[2021-12-22 17:28:14,101] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:17:00+00:00 [queued]>
[2021-12-22 17:28:14,102] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:28:14,102] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-22 17:28:14,102] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-22 17:28:14,111] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): super_resolution> on 2021-12-20 00:17:00+00:00
[2021-12-22 17:28:14,112] {standard_task_runner.py:52} INFO - Started process 23713 to run task
[2021-12-22 17:28:14,114] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline1', 'super_resolution', 'scheduled__2021-12-20T00:17:00+00:00', '--job-id', '103', '--raw', '--subdir', '/home/myamya/project/dockers/airflow/dags/hello_world.py', '--cfg-path', '/tmp/tmpfx13d8d8', '--error-file', '/tmp/tmplfcnm6i5']
[2021-12-22 17:28:14,114] {standard_task_runner.py:77} INFO - Job 103: Subtask super_resolution
[2021-12-22 17:28:14,132] {logging_mixin.py:109} INFO - Running <TaskInstance: data_pipeline1.super_resolution scheduled__2021-12-20T00:17:00+00:00 [running]> on host myamya
[2021-12-22 17:28:14,154] {taskinstance.py:1412} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yangjae
AIRFLOW_CTX_DAG_ID=data_pipeline1
AIRFLOW_CTX_TASK_ID=super_resolution
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T00:17:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T00:17:00+00:00
[2021-12-22 17:28:14,154] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-22 17:28:14,155] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker run -it -v /home/myamya/project/image_files/:/home/myamya/project/image_files/ sure:0.3 /bin/bash /home/myamya/project/init.sh ']
[2021-12-22 17:28:14,158] {subprocess.py:85} INFO - Output:
[2021-12-22 17:28:15,768] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDAFunctions.cpp:100.)
[2021-12-22 17:28:15,768] {subprocess.py:89} INFO -   return torch._C._cuda_getDeviceCount() > 0
[2021-12-22 17:28:16,769] {subprocess.py:89} INFO - Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to /opt/conda/lib/python3.8/site-packages/facexlib/weights/detection_Resnet50_Final.pth
[2021-12-22 17:28:16,770] {subprocess.py:89} INFO - 
[2021-12-22 17:28:19,669] {subprocess.py:89} INFO -   0% 0.00/104M [00:00<?, ?B/s]  0% 184k/104M [00:00<00:58, 1.88MB/s]  1% 968k/104M [00:00<00:44, 2.44MB/s]  4% 4.55M/104M [00:00<00:31, 3.35MB/s]  8% 8.05M/104M [00:00<00:22, 4.52MB/s] 13% 13.7M/104M [00:00<00:15, 6.26MB/s] 16% 16.8M/104M [00:00<00:11, 8.26MB/s] 21% 22.2M/104M [00:00<00:07, 11.1MB/s] 26% 27.6M/104M [00:00<00:05, 14.6MB/s] 30% 31.7M/104M [00:01<00:04, 17.9MB/s] 35% 37.0M/104M [00:01<00:03, 22.4MB/s] 41% 42.5M/104M [00:01<00:02, 27.4MB/s] 45% 47.1M/104M [00:01<00:01, 30.2MB/s] 50% 52.3M/104M [00:01<00:01, 34.8MB/s] 55% 57.7M/104M [00:01<00:01, 39.3MB/s] 60% 62.6M/104M [00:01<00:01, 39.5MB/s] 65% 67.6M/104M [00:01<00:00, 42.8MB/s] 70% 73.1M/104M [00:01<00:00, 46.2MB/s] 75% 78.0M/104M [00:01<00:00, 44.3MB/s] 79% 83.0M/104M [00:02<00:00, 46.5MB/s] 85% 88.4M/104M [00:02<00:00, 49.2MB/s] 89% 93.3M/104M [00:02<00:00, 46.6MB/s] 94% 98.2M/104M [00:02<00:00, 47.8MB/s] 99% 104M/104M [00:02<00:00, 50.2MB/s] 100% 104M/104M [00:02<00:00, 43.3MB/s]
[2021-12-22 17:28:19,813] {subprocess.py:89} INFO - Downloading: "https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth" to /opt/conda/lib/python3.8/site-packages/gfpgan/weights/GFPGANCleanv1-NoCE-C2.pth
[2021-12-22 17:28:19,814] {subprocess.py:89} INFO - 
[2021-12-22 17:28:27,753] {subprocess.py:89} INFO -   0% 0.00/332M [00:00<?, ?B/s]  0% 216k/332M [00:00<02:40, 2.17MB/s]  0% 720k/332M [00:00<02:50, 2.05MB/s]  1% 3.45M/332M [00:00<02:03, 2.80MB/s]  2% 7.92M/332M [00:00<01:27, 3.88MB/s]  4% 12.9M/332M [00:00<01:02, 5.37MB/s]  5% 17.2M/332M [00:00<00:45, 7.30MB/s]  6% 21.2M/332M [00:00<00:33, 9.71MB/s]  8% 25.5M/332M [00:01<00:25, 12.7MB/s]  9% 29.9M/332M [00:01<00:19, 16.2MB/s] 10% 34.0M/332M [00:01<00:15, 19.9MB/s] 12% 38.4M/332M [00:01<00:12, 24.0MB/s] 13% 42.6M/332M [00:01<00:10, 27.8MB/s] 14% 47.0M/332M [00:01<00:09, 31.6MB/s] 15% 51.4M/332M [00:01<00:08, 34.9MB/s] 17% 55.7M/332M [00:01<00:07, 37.4MB/s] 18% 60.3M/332M [00:01<00:07, 39.9MB/s] 19% 64.6M/332M [00:01<00:06, 41.4MB/s] 21% 69.2M/332M [00:02<00:06, 43.2MB/s] 22% 73.6M/332M [00:02<00:06, 44.1MB/s] 23% 78.1M/332M [00:02<00:05, 44.9MB/s] 25% 82.8M/332M [00:02<00:05, 46.0MB/s] 26% 87.3M/332M [00:02<00:05, 46.1MB/s] 28% 91.9M/332M [00:02<00:05, 46.8MB/s] 29% 96.4M/332M [00:02<00:05, 46.9MB/s] 30% 101M/332M [00:02<00:05, 47.4MB/s]  32% 106M/332M [00:02<00:04, 47.8MB/s] 33% 110M/332M [00:02<00:04, 47.9MB/s] 35% 115M/332M [00:03<00:04, 48.4MB/s] 36% 120M/332M [00:03<00:04, 46.2MB/s] 37% 124M/332M [00:03<00:04, 46.5MB/s] 39% 129M/332M [00:03<00:04, 47.5MB/s] 40% 134M/332M [00:03<00:04, 48.1MB/s] 42% 138M/332M [00:03<00:04, 48.3MB/s] 43% 143M/332M [00:03<00:04, 48.9MB/s] 44% 148M/332M [00:03<00:03, 48.8MB/s] 46% 153M/332M [00:03<00:03, 49.4MB/s] 47% 158M/332M [00:03<00:03, 49.8MB/s] 49% 162M/332M [00:04<00:03, 49.8MB/s] 50% 167M/332M [00:04<00:03, 50.1MB/s] 52% 172M/332M [00:04<00:03, 50.1MB/s] 53% 177M/332M [00:04<00:03, 50.3MB/s] 55% 182M/332M [00:04<00:03, 50.5MB/s] 56% 187M/332M [00:04<00:03, 50.5MB/s] 58% 191M/332M [00:04<00:02, 50.7MB/s] 59% 196M/332M [00:04<00:02, 50.6MB/s] 61% 201M/332M [00:04<00:02, 50.9MB/s] 62% 206M/332M [00:04<00:02, 50.9MB/s] 63% 211M/332M [00:05<00:02, 50.9MB/s] 65% 216M/332M [00:05<00:02, 51.2MB/s] 66% 221M/332M [00:05<00:02, 51.1MB/s] 68% 226M/332M [00:05<00:02, 51.3MB/s] 69% 231M/332M [00:05<00:02, 51.5MB/s] 71% 236M/332M [00:05<00:01, 51.3MB/s] 72% 241M/332M [00:05<00:01, 51.6MB/s] 74% 246M/332M [00:05<00:01, 51.5MB/s] 75% 250M/332M [00:05<00:01, 51.4MB/s] 77% 255M/332M [00:05<00:01, 51.7MB/s] 78% 260M/332M [00:06<00:01, 51.7MB/s] 80% 265M/332M [00:06<00:01, 51.7MB/s] 81% 270M/332M [00:06<00:01, 52.0MB/s] 83% 275M/332M [00:06<00:01, 51.9MB/s] 84% 280M/332M [00:06<00:01, 52.0MB/s] 86% 285M/332M [00:06<00:00, 52.0MB/s] 87% 290M/332M [00:06<00:00, 52.0MB/s] 89% 295M/332M [00:06<00:00, 52.1MB/s] 90% 300M/332M [00:06<00:00, 52.1MB/s] 92% 305M/332M [00:06<00:00, 52.1MB/s] 93% 310M/332M [00:07<00:00, 52.2MB/s] 95% 315M/332M [00:07<00:00, 52.0MB/s] 96% 320M/332M [00:07<00:00, 52.2MB/s] 98% 325M/332M [00:07<00:00, 51.9MB/s] 99% 330M/332M [00:07<00:00, 52.2MB/s]100% 332M/332M [00:07<00:00, 46.2MB/s]
[2021-12-22 17:28:27,917] {subprocess.py:89} INFO - Testing 0 2264
[2021-12-22 17:28:28,021] {subprocess.py:89} INFO - /opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
[2021-12-22 17:28:28,021] {subprocess.py:89} INFO -   warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
[2021-12-22 17:28:32,626] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-22 17:28:32,666] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=data_pipeline1, task_id=super_resolution, execution_date=20211220T001700, start_date=20211222T082814, end_date=20211222T082832
[2021-12-22 17:28:32,712] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-22 17:28:32,757] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
